Repository SWYP-3rd-muud/muud-backend, pull requests merged in 2024-09, with the labels that each got.

#187 feat: 세부 감정 API 구현 #182
  src/main/java/com/muud/emotion/controller/v1/EmotionControllerV1.java
  src/main/java/com/muud/emotion/domain/EmotionCard.java
  src/main/java/com/muud/emotion/domain/EmotionTag.java
  src/main/java/com/muud/emotion/domain/dto/EmotionListResponse.java
  src/main/java/com/muud/emotion/domain/dto/EmotionValue.java
  src/main/java/com/muud/emotion/domain/dto/TagListResponse.java
  src/main/java/com/muud/emotion/service/EmotionService.java
  src/test/java/com/muud/emotion/service/EmotionServiceTest.java
Labels: 기능개발

#193 test: Collection 테스트 작성 및 코드 스타일 수정
  src/main/java/com/muud/collection/controller/CollectionController.java
  src/main/java/com/muud/collection/domain/Collection.java
  src/main/java/com/muud/collection/domain/dto/CollectionDto.java
  src/main/java/com/muud/collection/service/CollectionService.java
  src/test/java/com/muud/collection/service/CollectionServiceTest.java
Labels: 테스트, 수정, 리팩터링

#199 refactor: 인가 방식 변경에 따른 메서드 수정 #198
  src/main/java/com/muud/bookmark/controller/BookmarkController.java
  src/main/java/com/muud/diary/controller/DiaryController.java
  src/main/java/com/muud/emotion/controller/EmotionController.java
  src/main/java/com/muud/emotion/controller/v1/EmotionControllerV1.java
  src/main/java/com/muud/report/controller/ReportController.java
Labels: 리팩터링

#200 refactor: 예외 처리 시스템 개편 #143
  src/main/java/com/muud/bookmark/exception/BookmarkErrorCode.java
  src/main/java/com/muud/bookmark/exception/BookmarkException.java
  src/main/java/com/muud/bookmark/service/BookmarkService.java
  src/main/java/com/muud/diary/exception/DiaryErrorCode.java
  src/main/java/com/muud/diary/exception/DiaryException.java
  src/main/java/com/muud/diary/service/DiaryService.java
  src/main/java/com/muud/global/error/GlobalExceptionHandler.java
  src/main/java/com/muud/global/exception/GlobalExceptionHandler.java
  src/main/java/com/muud/global/exception/response/ApiResponseError.java
  src/main/java/com/muud/global/exception/response/ApiSimpleError.java
  src/main/java/com/muud/global/exception/support/CustomException.java
  src/main/java/com/muud/global/exception/support/ErrorCode.java
  src/test/java/com/muud/diary/service/DiaryServiceTest.java
Labels: 리팩터링

#205 refactor: 기존 Auth 로직 삭제 및 util 추가 #201
  src/main/java/com/muud/auth/jwt/Auth.java
  src/main/java/com/muud/diary/service/DiaryService.java
  src/main/java/com/muud/global/config/SecurityConfig.java
  src/main/java/com/muud/global/util/SecurityUtils.java
  src/main/java/com/muud/user/controller/UserController.java
  src/main/java/com/muud/user/dto/UserInfo.java
  src/main/java/com/muud/user/dto/UserInfoUpdateRequest.java
  src/main/java/com/muud/user/entity/User.java
  src/main/java/com/muud/user/service/UserService.java
  src/test/java/com/muud/auth/service/AuthServiceTest.java
  src/test/java/com/muud/user/service/UserServiceTest.java
Labels: 기능개발, 리팩터링
